services:
  - docker  

matrix:
  include:
      script:
          - bash ../build-and-push-image-to-docker-hub.sh $TRAVIS_BUILD_NUMBER eventstore $DOCKER_HUB_USER $DOCKER_HUB_PASSWORD $TRAVIS_BRANCH


notifications:
  email:
    - gigapr@hotmail.com
