version: 1
update_configs:
  - package_manager: "go:dep"
    directory: "/src"
    update_schedule: "weekly"
  - package_manager: "go:dep"
    directory: "/client"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
